"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IPC = void 0;
exports.IPC = {
    WINDOW_MINIMIZE: "window:minimize",
    WINDOW_CLOSE: "window:close",
    WINDOW_MAXIMIZE: "window:maximize",
    DB_PING: "db:ping",
    DB_GET_FRAMEWORK: "db:get-framework",
    DB_GET_NODE: "db:get-node",
    DB_INIT_FRAMEWORK: "db:init-framework",
    DB_SUBMIT_NOTE: "db:submit-note",
    DB_CONFIRM_PLACEMENT: "db:confirm-placement",
    DB_ADD_NODE: "db:add-node",
    DB_UPDATE_NODE: "db:update-node",
    DB_DELETE_NODE: "db:delete-node",
    DB_MOVE_NODE: "db:move-node",
    DB_SEARCH: "db:search",
    DB_GET_TAGS: "db:get-tags",
    DB_EXPORT_DATA: "db:export-data",
    DB_IMPORT_DATA: "db:import-data",
    DB_GET_FRAMEWORKS: "db:get-frameworks",
    DB_CREATE_FRAMEWORK: "db:create-framework",
    DB_DELETE_FRAMEWORK: "db:delete-framework",
    DB_RENAME_FRAMEWORK: "db:rename-framework",
    DB_SET_CURRENT_FRAMEWORK: "db:set-current-framework",
    DB_GET_CURRENT_FRAMEWORK: "db:get-current-framework",
    DB_CREATE_SNAPSHOT: "db:create-snapshot",
    DB_GET_SNAPSHOTS: "db:get-snapshots",
    DB_RESTORE_SNAPSHOT: "db:restore-snapshot",
    DB_EXPORT_FRAMEWORK_MERMAID: "db:export-framework-mermaid",
    DB_EXPORT_FRAMEWORK_MARKDOWN: "db:export-framework-markdown",
    AI_ANALYZE_NOTE: "ai:analyze-note",
    AI_INSPECT_FRAMEWORK: "ai:inspect-framework",
    AI_SUMMARIZE_CONVERSATION: "ai:summarize-conversation",
    AI_SEARCH: "ai:search",
    AI_PRACTICE_REMINDER: "ai:practice-reminder",
    AI_GENERATE_DOMAIN_FRAMEWORK: "ai:generate-domain-framework",
    AI_REFINE_FRAMEWORK: "ai:refine-framework",
    APP_GET_CONFIG: "app:get-config",
    APP_SET_CONFIG: "app:set-config",
};
